[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry-proto = { version = "0.26.0", features = ["gen-tonic", "trace", "logs", "with-serde"]}
serde = {version = "1", features = ["derive"] }
serde_json = "1.0.128"

